### ISSUE TITLE
Should we really ping every user of large teams?

### ISSUE THREAD

**Issue by Filnor** [SOBotics/Hermes#3]
The RO team currently has 20 users. Should we really ping everyone of them? Maybe we should prioritize some of them (the more active ones) over other (which would still be pingeable with an additional parameter).

*FYI: [You can only ping 10 users at max with one chat message](https://meta.stackexchange.com/a/312385/371810)*

It was also [suggested](https://chat.stackoverflow.com/transcript/message/43766570#43766570) that only users that are currently in the room should be pinged.
But that throws up the question what to do when no one of the team is in the room.

Also add a command to list the members of a Team ([Like Smokey does](https://chat.stackoverflow.com/transcript/message/42352448#42352448)) and add an option to only ping all team members when specified by a parameter (and possibly a confirmation)

This way also non-regulars could know who's in the team and manually ping one.

**Comment by geisterfurz007** [comment]
I like the idea of chosing the most recently active users and the additional parameter to ping all.
The users can probably be sorted by activity with the chatrooms info page?

**Comment by geisterfurz007** [comment]
Another idea that came to my mind yesterday would be something like a `--here` flag that only pings those users that are currently in the room to narrow down the amount of people pinged (or flip it around and have that be the default behaviour).

**Comment by Filnor** [comment]
> or flip it around and have that be the default behaviour.

It would rather be that the default behavior. I think the idea is that we ping as few users as possible. Also note what Ashish mentioned in the [Nursery issue](https://github.com/SOBotics/Nursery/issues/5):

> Pinging has been a very controversial idea in the past, especially mass pings. If anyone has objections, please post a comment.

**Comment by Filnor** [comment]
The scope is currently to broad (pingable users are too many), so the used ChatOverflow method needs to be changed.

**Comment by Filnor** [comment]
@Jinx88909 That's the current behaviour except the first point. The problem is the underlying method of the chat lib that I currently use, which gives a list of users that are pingable. But this isn't the same as beeing in the room (You only count as not pingable if you weren't in the room for a longer time, like Tuna for example). But luckily, there is another method that I can test.

**Comment by jdd-software** [comment]
Pinging only last active RO could be very useful (you like to ping, troll in chat), hence no need to ping the world just 1... so in all cases this would be a nice command.

**Comment by Fortunate-MAN** [comment]
@Filnor I don't really know how SoundFlow's implemented, but if you're
looking for a method to get users who are in the room (not those who are
pingable), [such a method does exist](
https://github.com/Manishearth/ChatExchange/blob/master/chatexchange/rooms.py#L115-L120
).

**Comment by Filnor** [comment]
@Fortunate-MAN I'm aware of that method. [I currently use `get_pingable_users()`](https://github.com/SOBotics/Hermes/blob/master/soundflow/ping_team.py#L72) and a change of that to `get_current_users()` should  suffice.
